### ISSUE TITLE
Directional Example Full Black Shadows in build

### ISSUE THREAD

**Issue by LordHorusNL** [KevinComerford/zero_lab_renderer#2]
Hey guys first off great work on keeping the renderer updated, however i'm having a small problem.

When i load up the Directional example scene and build the game, all my shadows are completly solid black. Editor works great, build does not. (other example scenes seem to work fine)

Runnig Unity 2017.2.0F3

Anybody know how to fix this?

**Comment by KevinComerford** [comment]
I just tried out a build of that scene and it seemed fine. Did you let the lightbake finish before building? You can switch off Auto Generate in the lighting settings window and manually bake it if need be.
