### ISSUE TITLE
Cannot change renderViewportScale while cameras are rendering!

### ISSUE THREAD

**Issue by shiyamon** [KevinComerford/zero_lab_renderer#3]
I got this error when Adaptive Quality Enabled check box is on.

Cannot change renderViewportScale while cameras are rendering!
UnityEngine.XR.XRSettings:set_renderViewportScale(Single)
ValveCamera:UpdateAdaptiveQuality() (at Assets/Libraries/TheLabRenderer/Scripts/ValveCamera.cs:871)
ValveCamera:OnPreCull() (at Assets/Libraries/TheLabRenderer/Scripts/ValveCamera.cs:562)

Do you have any idea to fix this?
I use Unity 2017.3.1f1

**Comment by shiyamon** [comment]
OK it seems I found a workaround.
Changing two Macros from #if UNITY_5_5 to #if UNITY_5_5_OR_NEWER worked.

**Comment by KevinComerford** [comment]
Interesting. I can't seem to reproduce it. The #if UNITY_5_5 was a workaround fix before unity fixed it internally. https://github.com/ValveSoftware/the_lab_renderer/pull/17
