### ISSUE TITLE
Problem opening project

### ISSUE THREAD

**Issue by Wyattari** [KevinComerford/zero_lab_renderer#4]
Hello - this looks amazing, but when I try to open the project in Unity 2017.2.0f3 [I get lots of errors and warnings
](https://imgur.com/a/t3vQVaG)
It wont even render in the scene view.

**Comment by KevinComerford** [comment]
Most of that isn't too much of an issue. A lot of deprecated warnings in the recommended settings which need to be cleaned up.  I did accidently put a test scene file in the build settings which wasn't uploaded to git. To fix that, go to your build settings and clear it out. I'll remove it in the next release.

Let me know if you have more issues after clearing out the build settings.
