### ISSUE TITLE
Build issu

### ISSUE THREAD

**Issue by ezo09** [KevinComerford/zero_lab_renderer#5]
hi kevin,

First of all , thank you to continue developing the lab renderer, there is no better for the VR, you did an incredible job.
I'm currently working on a VR project with your version of the LAB and unity 2017.2.4, and I can't build, it freeze on Project-sharedassets0.assets ,  the cpu process keep working  alway at 100% on shadercompiler-UnityShaderCompiler.exe

any idea ?

**Comment by KevinComerford** [comment]
I realized this issue last night and I have pushed a fix. Go ahead and update it. It _should_ be faster to compile in general.

**Comment by ezo09** [comment]
It works great!
 
Thank you :)

do you intend to continue the development of the lab or it's finished for you ?

have a good day

**Comment by KevinComerford** [comment]
I am continuing to develop it. I am using it for production purposes and need to keep it functional. I also have some plans for further improvements in features, integrations, and performance.
